/*
Service for adding two numbers
URI: /eval
VERB: POST
Body 
    Expects:JSON {"filePath":Path_of_the_file}

* @authors
 *  - Kenneth Alfaro Barboza
 *  - Luis Fuentes Fuentes
 *  - Luis Eduardo Restrepo Veintemilla
 *  - Maria Angelica Robles Azofeifa
 *  - Royer Zuñiga Villareal
 * @version 1.0.0

*/
:- use_module(library(http/thread_httpd)).
:- use_module(library(http/http_dispatch)).
:- use_module(library(http/http_json)).
:- use_module(library(http/http_log)).

:- use_module(library(http/http_cors)).

:- use_module(library(http/html_write)).

:- use_module(library(readutil)).

% URL handlers.
:- http_handler('/eval', handle_request, [method(post)]).
:- http_handler('/', home, []).

handle_request(Request) :-
    http_read_json_dict(Request, Query),
    evaluate(Query, Solution),
    reply_json_dict(Solution).

server(Port) :-
    http_server(http_dispatch, [port(Port)]).

set_setting(http:logfile, 'service_log_file.log').

%%%%%%%%%%%%%%%%%%%%%%%%%% LOGIC %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Calls evaluation.
evaluate(_{fileName:X}, _{status: true, answer:Code, msg:'succeed'}) :-
    read_js_file_content(X, JsContent), 
    write_file(X, JsContent),
    Code is 0 % true
.
evaluate(_, _{accepted: false, answer:0, msg:'Error: failed evaluation'}).

read_js_file_content(FileName, Content) :-
    read_file_to_string(FileName, Content, []).

write_file(FileName, Content) :-
    get_time(T), stamp_date_time(T, date(Year, Month, Day, H, M, S, _, _, _), 'UTC'), 
    CRH is H - 6,
    NoDecimalsS is floor(S),
    atomic_list_concat([Year, '-', Month, '-', Day, ' '], '', Date),
    atomic_list_concat([CRH, ':', M, ':', NoDecimalsS], '', Time),
    open(FileName, write, Stream),
    atomic_list_concat(['// Generated by Prolog OFS 1.5 transpiler {', Date, Time, '}'], '', TimeStamp),
    write(Stream, TimeStamp), 
    nl(Stream),
    nl(Stream),
    write(Stream, Content),
    close(Stream)
.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

home(_Request) :-
        reply_html_page(title('Mini Add Service'),
                        [ h1('To use it:'),
                          p([h4('Send a post messsage'),
                             h4('URI:/add'),
                             h4('body: JSON data of the form {"a":number, "b":number}'),
                             h4('Service Responds with JSON as follows:'),
                             ul([li('{accepted:true, answer:a+b}    if data ok'),
                                 li('{accepted:false, answer:0, msg:some_error_message} othwerwise')])
                            ])
                        ]).

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% MAIN %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
:- initialization
    format('*** Starting Server ***~n', []),
    (current_prolog_flag(argv, [SPort | _]) -> true ; SPort='8000'),
    atom_number(SPort, Port),
    format('*** Serving on port ~d *** ~n', [Port]),
    set_setting_default(http:cors, [*]), % Allows cors for every
    server(Port).
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%