// Generated by Prolog OFS 2.0 transpiler {2023-11-22 14:10:40}
import {Iterate} from './iterate.mjs';

/* 
 test_case_4.ofs
 ternary
 string
 */
const printIt = it => console.log( it )
const parity_map_50 = new Iterate( 0, n => n + 1 ).filter( n => ( n != 0 ) ? `odd` : `even` ).cut( 50 )
parity_map_50.map( printIt )
