// Generated by Prolog OFS 2.0 transpiler {2023-11-22 15:30:36}
import {Iterate} from './iterate.mjs';

/* 
 test_case_3.ofs
 let 
 const
 iterate
 map
 cut
 filter
 call
 arithmethic
 relational
 lambda
 nested lambda
 */
let fifty = 50
const printIt = it => console.log( it )
const fifty_nats = new Iterate( 0, n => n + 1 ).cut( fifty )
const fiftyDivisibleBy2And3 = fifty_nats.filter( n => n % 2 == 0 && n % 3 == 0 )
DivisibleBy2And3.map( printIt )
